var cases = { 
			"how are you": "I am fine. What about you?",
			"lonely": "Go to Berlin, where you will not be bored and lonely.",
			"what are you doing": "I am talking to you.",
			"wearing": "Whatever you imagine.",
			"hungry": "How about eating something?",
			"bored": "How about playing some computer games?",
			"bad": "What happened?",
			"dumped": "There's plenty of fish.",
			"tired": "It's good to have enough sleep.",
			"m thirsty": "Get some drink!",
			"how old": "Age doesn't matter.",
			"your name": "You can call me whatever you want.",
			"what i said": "I understand.",
			"why": "You will find out why.",
			"like": "I like most things.",
			" hi": "Hello.",
			"hello": "Hi.",
			"marry": ":)",
			"bye": "Bye.",
			"yourself": "You will find out more about me by yourself.",
			"emily": "I am made by Emily.",
			"good": "Sounds good.",
			"idiot": "Please be nice.",
			"problem": "Problems always exist.",
			"sleepy": "Maybe it's time for bed?",
			randRes: ["Everything will be ok.", "Ok, I don't know what to say.", "Alright.", "Ok.", "Tell me about it.", "Oh?", "Fair enough."]
		};